<?php
include 'start.php';

$conn->query('Create TABLE PLEDGELIST (ID int AUTO_INCREMENT PRIMARY KEY,
 UID int UNIQUE NOT NULL, PID int UNIQUE NOT NULL, FOREIGN KEY (UID) REFERENCES USER(ID),
  FOREIGN KEY (PID) REFERENCES FARMPOST(PID))');

?>